# Generated by Django 4.0.6 on 2022-08-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('t_name', models.CharField(blank=True, max_length=250, null=True)),
                ('t_id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_status', models.CharField(blank=True, max_length=250, null=True)),
                ('start_Time', models.TimeField(blank=True, null=True)),
                ('end_Time', models.TimeField(blank=True, null=True)),
                ('created_Date', models.DateField(blank=True, null=True)),
                ('approval_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_Manager', models.CharField(blank=True, max_length=300, null=True)),
                ('task_Description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
